on:
  push:
    branches:
      - production

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Ou '16', dependendo de sua preferência

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 154.56.48.224
          port: 21
          username: u139152663
          password: h86e-cLyBav4+f$
          server-dir: /public_html/imobi/
          exclude: |
            **/.github*
            **/.github*/**
            **/uploads/**
            # **/system/**
            # .env
            fileToExclude.txt
